[workspace]
# This line tells cargo-dist that the Rust project is in the 'src-tauri' folder.
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.2"
# CI backends to support
ci = "github"
# By removing the 'installers' line, cargo-dist will only build the default archives (.zip for windows)
# A list of extra files and folders to include in the final archive
include = ["batch-scripts", "licenses"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
