[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.2"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["./RVFXE/batch-scripts"]

[build.dependencies]
apt = [
    "pkg-config",
    "libgtk-3-dev",
    "libglib2.0-dev",
    "libpango1.0-dev",
    "libcairo2-dev",
    "libgdk-pixbuf2.0-dev",
    "libatk1.0-dev",
    "gtk+3-devel"
]
